# Generated by Django 4.1.5 on 2023-01-04 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("date", models.DateTimeField(verbose_name="bring date")),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("name", models.CharField(max_length=200)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard.customer",
                    ),
                ),
            ],
        ),
    ]
